DROP TABLE IF EXISTS WorksIn;
DROP TABLE IF EXISTS Trained;
DROP TABLE IF EXISTS AssignedTo;
DROP TABLE IF EXISTS Volunteer;
DROP TABLE IF EXISTS Project;
DROP TABLE IF EXISTS Training;
DROP TABLE IF EXISTS Shift;
DROP TABLE IF EXISTS VolunteerType;
DROP TABLE IF EXISTS Manager;

