insert into VolunteerType  (VolunteerTypeID, TypeName) values (1, 'Patient Transport');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (2, 'Reception Assistance');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (3, 'Emergency Room Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (4, 'Pediatric Ward Assistance');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (5, 'Elderly Care Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (6, 'Surgical Waiting Room Guide');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (7, 'Cancer Patient Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (8, 'Mental Health Companion');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (9, 'Physical Therapy Aid');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (10, 'Art Therapy Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (11, 'Music Therapy Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (12, 'Playroom Supervision');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (13, 'Waiting Room Hospitality');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (14, 'ICU Family Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (15, 'Bereavement Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (16, 'Blood Bank Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (17, 'Lab Sample Courier');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (18, 'Pharmacy Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (19, 'Wheelchair Assistance');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (20, 'Medical Records Organization');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (21, 'Pediatric Play Therapy');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (22, 'Clerical Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (23, 'Spiritual Care');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (24, 'Library Cart Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (25, 'Gift Shop Helper');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (26, 'Therapy Animal Handler');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (27, 'Food Delivery for Patients');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (28, 'Language Interpretation');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (29, 'Chaplaincy Assistance');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (30, 'Dental Clinic Helper');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (31, 'Physiotherapy Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (32, 'Hospice Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (33, 'Family Liaison');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (34, 'Pre-Op Companion');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (35, 'Recovery Room Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (36, 'Vision Screening Helper');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (37, 'Neonatal ICU Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (38, 'Health Education Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (39, 'Nutrition Counseling Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (40, 'Hand Hygiene Advocate');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (41, 'Community Health Outreach');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (42, 'Flu Shot Clinic Helper');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (43, 'Diabetes Education Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (44, 'Stroke Recovery Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (45, 'Patient Surveys and Feedback');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (46, 'Pain Management Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (47, 'Rehabilitation Therapy Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (48, 'Home Care Coordination');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (49, 'Organ Donation Awareness');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (50, 'Occupational Therapy Helper');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (51, 'Infant Care Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (52, 'Blood Pressure Screening');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (53, 'Oncology Ward Companion');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (54, 'Child Life Specialist Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (55, 'Elderly Mobility Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (56, 'Bereavement Counseling');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (57, 'Prosthetics and Orthotics Helper');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (58, 'Hygiene Kit Distribution');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (59, 'COVID-19 Testing Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (60, 'Vaccination Center Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (61, 'Waiting Room Storytelling');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (62, 'Post-Surgery Rehabilitation Aid');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (63, 'Charity Fundraising');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (64, 'Volunteer Trainer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (65, 'Community Health Events');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (66, 'End-of-Life Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (67, 'Meditation & Mindfulness Coaching');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (68, 'Grief Counseling');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (69, 'Neurology Clinic Helper');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (70, 'Nutrition Program Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (71, 'Social Work Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (72, 'Prenatal Education Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (73, 'Hospital Gardening Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (74, 'Sensory Room Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (75, 'Public Health Research');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (76, 'Cancer Awareness Educator');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (77, 'Genetic Counseling Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (78, 'Hearing Screening Helper');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (79, 'Home Visit Coordination');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (80, 'Emergency Preparedness Educator');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (81, 'Family Counseling Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (82, 'Disability Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (83, 'Pet Therapy Coordinator');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (84, 'Volunteer Coordinator Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (85, 'Ambulance Support Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (86, 'Disaster Relief Planning');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (87, 'Data Entry for Medical Research');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (88, 'Breastfeeding Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (89, 'Prenatal Yoga Coach');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (90, 'Domestic Violence Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (91, 'Wheelchair Maintenance');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (92, 'Heart Disease Awareness');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (93, 'Dialysis Center Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (94, 'Infant Massage Therapy');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (95, 'Senior Companion');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (96, 'Home Rehabilitation Assistance');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (97, 'Cognitive Therapy Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (98, 'Crisis Hotline Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (99, 'Preventative Care Advocate');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (100, 'Patient Wellbeing Surveys');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (101, 'Meditation for Pain Relief');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (102, 'Reflexology Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (103, 'Newborn Care Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (104, 'Peer Support Groups');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (105, 'Postpartum Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (106, 'Smoking Cessation Coaching');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (107, 'Virtual Health Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (108, 'Pediatric Feeding Therapy');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (109, 'Hospice Music Therapy');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (110, 'Geriatric Fitness Coaching');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (111, 'Dementia Support Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (112, 'Chronic Illness Peer Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (113, 'Volunteer Chaplaincy');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (114, 'Healthcare Advocacy');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (115, 'Children''s Oncology Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (116, 'Family Support for Terminally Ill');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (117, 'Handwriting Therapy Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (118, 'Public Health Lectures');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (119, 'AIDS/HIV Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (120, 'Hygiene Awareness Programs');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (121, 'Maternity Ward Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (122, 'Palliative Care Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (123, 'Therapeutic Storytelling');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (124, 'Patient Rights Advocacy');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (125, 'CPR & First Aid Trainer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (126, 'Ergonomics Education');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (127, 'Social Media for Health Campaigns');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (128, 'Support for Hospitalized Veterans');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (129, 'Organ Transplant Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (130, 'Adolescent Health Mentor');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (131, 'Community Nutrition Coach');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (132, 'Breast Cancer Screening Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (133, 'Physical Activity Coach');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (134, 'Caregiver Respite Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (135, 'Mental Wellness Hotline');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (136, 'Trauma Recovery Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (137, 'Rehabilitation Games Facilitator');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (138, 'Sensory Integration Therapy');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (139, 'Accessibility Advocacy');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (140, 'Therapy Dogs Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (141, 'Chaplain Services');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (142, 'Genetic Testing Counselor');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (143, 'Cancer Rehabilitation Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (144, 'Stroke Prevention Education');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (145, 'Grief Support Groups');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (146, 'Patient Empowerment Programs');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (147, 'Post-Surgical Home Care');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (148, 'Smoking Awareness Campaigns');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (149, 'Hospital Equipment Organizer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (150, 'Care Plan Navigator');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (151, 'Speech Therapy Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (152, 'Allergy Education Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (153, 'Endocrinology Clinic Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (154, 'Holistic Medicine Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (155, 'Herbal Therapy Educator');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (156, 'Preventative Screenings');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (157, 'Pediatric Orthopedics Helper');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (158, 'Psychological First Aid');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (159, 'Functional Medicine Educator');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (160, 'Public Health Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (161, 'Geriatric Nutritionist');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (162, 'Oncology Massage Therapy');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (163, 'Chronic Pain Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (164, 'Speech & Language Screening');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (165, 'Concussion Awareness Educator');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (166, 'Cognitive Behavioral Therapy Aid');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (167, 'Infant CPR Trainer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (168, 'Family Medical Advocacy');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (169, 'Cancer Survivorship Coaching');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (170, 'Domestic Abuse Awareness');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (171, 'Handwashing Awareness Campaign');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (172, 'Neurological Support Groups');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (173, 'Art for Healing Programs');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (174, 'Patient Peer Mentorship');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (175, 'Substance Abuse Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (176, 'Mental Health Screening Clinics');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (177, 'Blood Sugar Testing Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (178, 'Physical Fitness for Seniors');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (179, 'Medical Conference Assistance');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (180, 'Healthcare Research Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (181, 'Youth Health Awareness');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (182, 'Stress Management for Patients');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (183, 'Autism Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (184, 'Crisis Intervention');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (185, 'Burn Unit Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (186, 'Alzheimer''s Care Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (187, 'Brain Injury Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (188, 'Ergonomic Training');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (189, 'Refugee Health Assistance');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (190, 'Respiratory Therapy Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (191, 'PTSD Support Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (192, 'Suicide Prevention Hotlines');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (193, 'Clinical Trial Patient Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (194, 'Diabetes Peer Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (195, 'Men’s Health Education');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (196, 'Women’s Health Awareness');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (197, 'Prenatal Nutrition Coaching');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (198, 'Dermatology Clinic Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (199, 'Pediatric Neurology Helper');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (200, 'Patient Navigator');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (201, 'Mental Health Crisis Responder');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (202, 'Cardiology Clinic Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (203, 'Exercise Therapy Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (204, 'Wound Care Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (205, 'Virtual Patient Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (206, 'Support for Rare Diseases');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (207, 'Cultural Health Advocacy');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (208, 'Nutrition Planning for Chronic Illness');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (209, 'Aging-in-Place Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (210, 'Virtual Medical Scribing');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (211, 'Burn Survivor Peer Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (212, 'Bilingual Health Educator');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (213, 'Behavioral Therapy Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (214, 'Deaf and Hard-of-Hearing Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (215, 'Vision Impairment Aid');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (216, 'Preventative Health Coaching');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (217, 'Neurodiversity Awareness');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (218, 'Post-Traumatic Growth Coaching');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (219, 'Body Positivity in Healthcare');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (220, 'Disability Rights Awareness');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (221, 'Kidney Transplant Coordination');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (222, 'Anemia Awareness Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (223, 'Surgical Recovery Assistance');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (224, 'Postpartum Doula Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (225, 'Chemotherapy Infusion Center Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (226, 'Speech Impairment Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (227, 'Balance & Fall Prevention');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (228, 'Clinical Nutrition Research');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (229, 'Teen Mental Health Advocate');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (230, 'Support Groups for Rare Disorders');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (231, 'Transgender Healthcare Advocate');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (232, 'Breastfeeding Peer Counselor');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (233, 'Hearing Loss Prevention');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (234, 'Alternative Therapy Guide');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (235, 'Emergency Disaster Response Training');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (236, 'Chronic Fatigue Syndrome Awareness');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (237, 'Home Health Care Assistance');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (238, 'Workplace Health & Safety Trainer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (239, 'High-Risk Pregnancy Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (240, 'Pulmonary Rehabilitation Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (241, 'Pediatric Chronic Disease Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (242, 'Emergency Shelter Medical Aid');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (243, 'Acupuncture for Cancer Patients');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (244, 'Animal-Assisted Therapy in Hospitals');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (245, 'Cancer Prevention Educator');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (246, 'Virtual Mental Health Peer Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (247, 'Family Planning Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (248, 'Spinal Cord Injury Peer Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (249, 'LGBTQ+ Health Advocacy');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (250, 'Athletic Therapy Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (251, 'Acupressure Therapy Educator');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (252, 'Integrated Healthcare Coordination');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (253, 'Pediatric Rehabilitation');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (254, 'Diabetes Meal Planning Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (255, 'Sleep Hygiene Education');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (256, 'Energy Healing Educator');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (257, 'Physical Disability Advocacy');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (258, 'Health Literacy Program');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (259, 'Online Support for Isolated Patients');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (260, 'Cross-Cultural Health Educator');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (261, 'Clinical Ethics Committee Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (262, 'Digestive Health Awareness');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (263, 'Occupational Health & Safety Educator');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (264, 'Microbiome Research Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (265, 'Traditional Medicine Awareness');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (266, 'Behavioral Health Coaching');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (267, 'Cognitive Rehabilitation');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (268, 'Community Mental Health Speaker');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (269, 'Disability Employment Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (270, 'Pediatric Oncology Art Therapy');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (271, 'Food Allergy Awareness');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (272, 'Anxiety Management in Hospitals');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (273, 'Medication Management Assistance');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (274, 'Herbal Medicine Research');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (275, 'Faith-Based Health Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (276, 'Pain Management Education');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (277, 'Pediatric Palliative Care Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (278, 'Rural Health Access Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (279, 'Speech Recovery Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (280, 'Assistive Technology Educator');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (281, 'Cancer Immunotherapy Education');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (282, 'Geriatric Exercise Programs');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (283, 'Military Veterans Health Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (284, 'Trauma-Focused Counseling');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (285, 'Preventative Dentistry Education');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (286, 'Functional Neurology Awareness');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (287, 'Women''s Preventative Health');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (288, 'Memory Care Engagement');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (289, 'Emergency Medical Interpreter');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (290, 'Online Counseling Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (291, 'Virtual Rehabilitation Coaching');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (292, 'Patient Transport');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (293, 'Reception Assistance');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (294, 'Emergency Room Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (295, 'Pediatric Ward Assistance');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (296, 'Elderly Care Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (297, 'Surgical Waiting Room Guide');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (298, 'Cancer Patient Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (299, 'Mental Health Companion');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (300, 'Physical Therapy Aid');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (301, 'Art Therapy Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (302, 'Music Therapy Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (303, 'Playroom Supervision');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (304, 'Waiting Room Hospitality');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (305, 'ICU Family Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (306, 'Bereavement Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (307, 'Blood Bank Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (308, 'Lab Sample Courier');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (309, 'Pharmacy Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (310, 'Wheelchair Assistance');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (311, 'Medical Records Organization');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (312, 'Pediatric Play Therapy');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (313, 'Clerical Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (314, 'Spiritual Care');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (315, 'Library Cart Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (316, 'Gift Shop Helper');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (317, 'Therapy Animal Handler');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (318, 'Food Delivery for Patients');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (319, 'Language Interpretation');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (320, 'Chaplaincy Assistance');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (321, 'Dental Clinic Helper');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (322, 'Physiotherapy Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (323, 'Hospice Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (324, 'Family Liaison');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (325, 'Pre-Op Companion');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (326, 'Recovery Room Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (327, 'Vision Screening Helper');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (328, 'Neonatal ICU Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (329, 'Health Education Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (330, 'Nutrition Counseling Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (331, 'Hand Hygiene Advocate');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (332, 'Community Health Outreach');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (333, 'Flu Shot Clinic Helper');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (334, 'Diabetes Education Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (335, 'Stroke Recovery Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (336, 'Patient Surveys and Feedback');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (337, 'Pain Management Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (338, 'Rehabilitation Therapy Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (339, 'Home Care Coordination');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (340, 'Organ Donation Awareness');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (341, 'Occupational Therapy Helper');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (342, 'Infant Care Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (343, 'Blood Pressure Screening');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (344, 'Oncology Ward Companion');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (345, 'Child Life Specialist Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (346, 'Elderly Mobility Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (347, 'Bereavement Counseling');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (348, 'Prosthetics and Orthotics Helper');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (349, 'Hygiene Kit Distribution');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (350, 'COVID-19 Testing Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (351, 'Vaccination Center Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (352, 'Waiting Room Storytelling');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (353, 'Post-Surgery Rehabilitation Aid');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (354, 'Charity Fundraising');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (355, 'Volunteer Trainer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (356, 'Community Health Events');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (357, 'End-of-Life Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (358, 'Meditation & Mindfulness Coaching');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (359, 'Grief Counseling');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (360, 'Neurology Clinic Helper');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (361, 'Nutrition Program Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (362, 'Social Work Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (363, 'Prenatal Education Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (364, 'Hospital Gardening Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (365, 'Sensory Room Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (366, 'Public Health Research');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (367, 'Cancer Awareness Educator');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (368, 'Genetic Counseling Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (369, 'Hearing Screening Helper');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (370, 'Home Visit Coordination');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (371, 'Emergency Preparedness Educator');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (372, 'Family Counseling Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (373, 'Disability Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (374, 'Pet Therapy Coordinator');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (375, 'Volunteer Coordinator Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (376, 'Ambulance Support Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (377, 'Disaster Relief Planning');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (378, 'Data Entry for Medical Research');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (379, 'Breastfeeding Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (380, 'Prenatal Yoga Coach');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (381, 'Domestic Violence Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (382, 'Wheelchair Maintenance');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (383, 'Heart Disease Awareness');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (384, 'Dialysis Center Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (385, 'Infant Massage Therapy');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (386, 'Senior Companion');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (387, 'Home Rehabilitation Assistance');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (388, 'Cognitive Therapy Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (389, 'Crisis Hotline Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (390, 'Preventative Care Advocate');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (391, 'Patient Wellbeing Surveys');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (392, 'Meditation for Pain Relief');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (393, 'Reflexology Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (394, 'Newborn Care Volunteer');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (395, 'Peer Support Groups');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (396, 'Postpartum Support');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (397, 'Smoking Cessation Coaching');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (398, 'Virtual Health Assistant');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (399, 'Pediatric Feeding Therapy');
insert into VolunteerType  (VolunteerTypeID, TypeName) values (400, 'Hospice Music Therapy');
